/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author DELL
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dadhboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        btn_add_credit = new javax.swing.JButton();
        btn_edit_credit = new javax.swing.JButton();
        btn_view_all_credit = new javax.swing.JButton();
        btn_view_credit = new javax.swing.JButton();
        btn_remove_credit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_credits = new javax.swing.JTable();
        lbl_copyright = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_title.setText("DASHBOARD | CREDIT MANAGER");

        btn_add_credit.setText("ADD CREDIT REQUEST");
        btn_add_credit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_creditActionPerformed(evt);
            }
        });

        btn_edit_credit.setText("EDIT CREDIT");
        btn_edit_credit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_creditActionPerformed(evt);
            }
        });

        btn_view_all_credit.setText("View All Credit");

        btn_view_credit.setText("View Credit");

        btn_remove_credit.setText("Remove Request");
        btn_remove_credit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_remove_creditActionPerformed(evt);
            }
        });

        tbl_credits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "S.No", "Credit Id", "Customer Name", "Credit Request At", "Credit Status"
            }
        ));
        jScrollPane1.setViewportView(tbl_credits);

        lbl_copyright.setText("Copyright 2024 @ Credit Manager | Developed by DAV sixth sem");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btn_add_credit)
                        .addGap(18, 18, 18)
                        .addComponent(btn_edit_credit)
                        .addGap(18, 18, 18)
                        .addComponent(btn_remove_credit)
                        .addGap(30, 30, 30)
                        .addComponent(btn_view_all_credit)
                        .addGap(28, 28, 28)
                        .addComponent(btn_view_credit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(lbl_title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_copyright, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbl_title)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add_credit)
                    .addComponent(btn_edit_credit)
                    .addComponent(btn_view_all_credit)
                    .addComponent(btn_view_credit)
                    .addComponent(btn_remove_credit))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lbl_copyright)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_add_creditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_creditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_add_creditActionPerformed

    private void btn_edit_creditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_creditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit_creditActionPerformed

    private void btn_remove_creditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_remove_creditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_remove_creditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_credit;
    private javax.swing.JButton btn_edit_credit;
    private javax.swing.JButton btn_remove_credit;
    private javax.swing.JButton btn_view_all_credit;
    private javax.swing.JButton btn_view_credit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_copyright;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTable tbl_credits;
    // End of variables declaration//GEN-END:variables
}
