/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author DELL
 */
public class EditCredit extends javax.swing.JFrame {

    /**
     * Creates new form EditCredit
     */
    public EditCredit() {
        initComponents();
        edit_tab_pane.add(CustomerDetail,"Customer Details",0);
        edit_tab_pane.add(PropertyDetail,"Property Details",1);
        edit_tab_pane.add(IncomeDetail,"Income Details",2);
        edit_tab_pane.add(CreditDetail,"Credit Details",3);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CustomerDetail = new javax.swing.JInternalFrame();
        panel_customer = new javax.swing.JPanel();
        lbl_full_name = new javax.swing.JLabel();
        text_full_name = new javax.swing.JTextField();
        lbl_dob = new javax.swing.JLabel();
        text_dob = new javax.swing.JTextField();
        lbl_address = new javax.swing.JLabel();
        text_address = new javax.swing.JTextField();
        PropertyDetail = new javax.swing.JInternalFrame();
        panel_property = new javax.swing.JPanel();
        lbl_property_validation = new javax.swing.JLabel();
        text_property_validation = new javax.swing.JTextField();
        lbl_property_type = new javax.swing.JLabel();
        text_property_type = new javax.swing.JTextField();
        lbl_valuation_date = new javax.swing.JLabel();
        text_valuation_date = new javax.swing.JTextField();
        IncomeDetail = new javax.swing.JInternalFrame();
        panel_income = new javax.swing.JPanel();
        lbl_income_source = new javax.swing.JLabel();
        text_income_source = new javax.swing.JTextField();
        lbl_annual_income = new javax.swing.JLabel();
        text_annual_income = new javax.swing.JTextField();
        CreditDetail = new javax.swing.JInternalFrame();
        panel_credit = new javax.swing.JPanel();
        lbl_credit_type = new javax.swing.JLabel();
        text_credit_type = new javax.swing.JTextField();
        lbl_credit_amount = new javax.swing.JLabel();
        text_credit_amount = new javax.swing.JTextField();
        lbl_is_eligible = new javax.swing.JLabel();
        text_is_eligible = new javax.swing.JTextField();
        lbl_credit_status = new javax.swing.JLabel();
        text_credit_status = new javax.swing.JTextField();
        lbl_title = new javax.swing.JLabel();
        edit_tab_pane = new javax.swing.JTabbedPane();

        CustomerDetail.setVisible(true);

        panel_customer.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer_Details"));

        lbl_full_name.setText("Full Name:");

        text_full_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_full_nameActionPerformed(evt);
            }
        });

        lbl_dob.setText("Date of Birth");

        text_dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_dobActionPerformed(evt);
            }
        });

        lbl_address.setText("Permanent Address:");

        javax.swing.GroupLayout panel_customerLayout = new javax.swing.GroupLayout(panel_customer);
        panel_customer.setLayout(panel_customerLayout);
        panel_customerLayout.setHorizontalGroup(
            panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_customerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_full_name)
                    .addComponent(lbl_dob)
                    .addComponent(lbl_address))
                .addGap(37, 37, 37)
                .addGroup(panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_full_name)
                    .addComponent(text_dob)
                    .addComponent(text_address, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_customerLayout.setVerticalGroup(
            panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_customerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_full_name)
                    .addComponent(text_full_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_dob)
                    .addComponent(text_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_address)
                    .addComponent(text_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CustomerDetailLayout = new javax.swing.GroupLayout(CustomerDetail.getContentPane());
        CustomerDetail.getContentPane().setLayout(CustomerDetailLayout);
        CustomerDetailLayout.setHorizontalGroup(
            CustomerDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
            .addGroup(CustomerDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CustomerDetailLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel_customer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        CustomerDetailLayout.setVerticalGroup(
            CustomerDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
            .addGroup(CustomerDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerDetailLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        PropertyDetail.setVisible(true);

        panel_property.setBorder(javax.swing.BorderFactory.createTitledBorder("Property_Details"));

        lbl_property_validation.setText("Property Validation:");

        text_property_validation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_property_validationActionPerformed(evt);
            }
        });

        lbl_property_type.setText("Propert Type:");

        lbl_valuation_date.setText("Valuation Date:");

        text_valuation_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_valuation_dateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_propertyLayout = new javax.swing.GroupLayout(panel_property);
        panel_property.setLayout(panel_propertyLayout);
        panel_propertyLayout.setHorizontalGroup(
            panel_propertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_propertyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_propertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_property_validation)
                    .addComponent(lbl_valuation_date)
                    .addComponent(lbl_property_type))
                .addGap(35, 35, 35)
                .addGroup(panel_propertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_valuation_date)
                    .addComponent(text_property_validation, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_property_type, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        panel_propertyLayout.setVerticalGroup(
            panel_propertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_propertyLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_propertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_property_validation)
                    .addComponent(text_property_validation, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_propertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_property_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_property_type, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_propertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_valuation_date)
                    .addComponent(text_valuation_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PropertyDetailLayout = new javax.swing.GroupLayout(PropertyDetail.getContentPane());
        PropertyDetail.getContentPane().setLayout(PropertyDetailLayout);
        PropertyDetailLayout.setHorizontalGroup(
            PropertyDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PropertyDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_property, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        PropertyDetailLayout.setVerticalGroup(
            PropertyDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PropertyDetailLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panel_property, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        IncomeDetail.setVisible(true);

        panel_income.setBorder(javax.swing.BorderFactory.createTitledBorder("Income  Details\n"));

        lbl_income_source.setText("Income Source:");

        text_income_source.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_income_sourceActionPerformed(evt);
            }
        });

        lbl_annual_income.setText("Annual Income");

        javax.swing.GroupLayout panel_incomeLayout = new javax.swing.GroupLayout(panel_income);
        panel_income.setLayout(panel_incomeLayout);
        panel_incomeLayout.setHorizontalGroup(
            panel_incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_incomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_income_source)
                    .addComponent(lbl_annual_income))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_income_source, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                    .addComponent(text_annual_income))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_incomeLayout.setVerticalGroup(
            panel_incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_incomeLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panel_incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_income_source)
                    .addComponent(text_income_source, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panel_incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_annual_income)
                    .addComponent(text_annual_income, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout IncomeDetailLayout = new javax.swing.GroupLayout(IncomeDetail.getContentPane());
        IncomeDetail.getContentPane().setLayout(IncomeDetailLayout);
        IncomeDetailLayout.setHorizontalGroup(
            IncomeDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(IncomeDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(IncomeDetailLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel_income, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        IncomeDetailLayout.setVerticalGroup(
            IncomeDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
            .addGroup(IncomeDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(IncomeDetailLayout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(panel_income, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(47, Short.MAX_VALUE)))
        );

        CreditDetail.setVisible(true);

        panel_credit.setBorder(javax.swing.BorderFactory.createTitledBorder("Credit Details"));

        lbl_credit_type.setText("Credit Type:");

        text_credit_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_credit_typeActionPerformed(evt);
            }
        });

        lbl_credit_amount.setText("Credit Amount");

        lbl_is_eligible.setText("Is Eligible");

        lbl_credit_status.setText("Credit Status:");

        javax.swing.GroupLayout panel_creditLayout = new javax.swing.GroupLayout(panel_credit);
        panel_credit.setLayout(panel_creditLayout);
        panel_creditLayout.setHorizontalGroup(
            panel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_creditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_creditLayout.createSequentialGroup()
                        .addGroup(panel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_credit_type)
                            .addComponent(lbl_credit_amount)
                            .addComponent(lbl_is_eligible))
                        .addGap(37, 37, 37)
                        .addGroup(panel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(text_credit_type, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                                .addComponent(text_credit_amount))
                            .addComponent(text_credit_status, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)))
                    .addGroup(panel_creditLayout.createSequentialGroup()
                        .addComponent(lbl_credit_status)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(text_is_eligible, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_creditLayout.setVerticalGroup(
            panel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_creditLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_credit_type)
                    .addComponent(text_credit_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_credit_amount)
                    .addComponent(text_credit_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_is_eligible)
                    .addComponent(text_credit_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_credit_status)
                    .addComponent(text_is_eligible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CreditDetailLayout = new javax.swing.GroupLayout(CreditDetail.getContentPane());
        CreditDetail.getContentPane().setLayout(CreditDetailLayout);
        CreditDetailLayout.setHorizontalGroup(
            CreditDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
            .addGroup(CreditDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CreditDetailLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel_credit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        CreditDetailLayout.setVerticalGroup(
            CreditDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
            .addGroup(CreditDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CreditDetailLayout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(panel_credit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_title.setText("Edit Credit Request | CREDIT MANAGER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(edit_tab_pane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lbl_title)
                .addGap(27, 27, 27)
                .addComponent(edit_tab_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_full_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_full_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_full_nameActionPerformed

    private void text_dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_dobActionPerformed

    private void text_property_validationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_property_validationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_property_validationActionPerformed

    private void text_valuation_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_valuation_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_valuation_dateActionPerformed

    private void text_income_sourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_income_sourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_income_sourceActionPerformed

    private void text_credit_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_credit_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_credit_typeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCredit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame CreditDetail;
    private javax.swing.JInternalFrame CustomerDetail;
    private javax.swing.JInternalFrame IncomeDetail;
    private javax.swing.JInternalFrame PropertyDetail;
    private javax.swing.JTabbedPane edit_tab_pane;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_annual_income;
    private javax.swing.JLabel lbl_credit_amount;
    private javax.swing.JLabel lbl_credit_status;
    private javax.swing.JLabel lbl_credit_type;
    private javax.swing.JLabel lbl_dob;
    private javax.swing.JLabel lbl_full_name;
    private javax.swing.JLabel lbl_income_source;
    private javax.swing.JLabel lbl_is_eligible;
    private javax.swing.JLabel lbl_property_type;
    private javax.swing.JLabel lbl_property_validation;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_valuation_date;
    private javax.swing.JPanel panel_credit;
    private javax.swing.JPanel panel_customer;
    private javax.swing.JPanel panel_income;
    private javax.swing.JPanel panel_property;
    private javax.swing.JTextField text_address;
    private javax.swing.JTextField text_annual_income;
    private javax.swing.JTextField text_credit_amount;
    private javax.swing.JTextField text_credit_status;
    private javax.swing.JTextField text_credit_type;
    private javax.swing.JTextField text_dob;
    private javax.swing.JTextField text_full_name;
    private javax.swing.JTextField text_income_source;
    private javax.swing.JTextField text_is_eligible;
    private javax.swing.JTextField text_property_type;
    private javax.swing.JTextField text_property_validation;
    private javax.swing.JTextField text_valuation_date;
    // End of variables declaration//GEN-END:variables
}
